fest(section): added helper funtions for manipulationd sections
AananthV/Notes-Backend pull request #4
Opened 2020-09-03 19:00 UTC by bestinbthomas

2020-09-04 04:30 UTC, Pavi114 requested changes

2020-09-04 04:30 UTC, Pavi114 commented on src/helpers/section.ts
> +    return await SectionModel.create({ cells: cells ? cells : [] });
A section should have atleast one cell. So create a cell and push it to section?

2020-09-04 04:30 UTC, Pavi114 commented on src/helpers/section.ts
> +    return await SectionModel.update({ _id: id }, { $push: { cells: cell } });
There should be a max limit on the number of cells a section can have. Add a check for that?

2020-09-04 04:38 UTC, Pavi114 commented on src/helpers/section.ts
> +    return await SectionModel.findById(id);
Change type of id to ObjectId

2020-09-04 05:11 UTC, Jayashrri requested changes

2020-09-04 05:11 UTC, Jayashrri commented on src/helpers/section.ts
> +export const getSection = async (id: string) => {
Change id type to ObjectId

2020-09-04 05:11 UTC, Jayashrri commented on src/helpers/section.ts
> +import SectionModel from '../Models/section.model';
Use camelCase please

2020-09-07 03:51 UTC, AananthV commented on src/helpers/section.ts
> +import SectionModel from '../Models/section.model';
While loading models / external files CapsIsBetter

2020-09-07 13:44 UTC, Pavi114 approved these changes

2020-09-07 13:45 UTC, merged